import {TYPES,KINDS,qty,money,today,monthRange,status,positions,summary,demo,normalizeLine} from './engine.js';
import {db,load,postOperation,cancelOperation,saveOpening,saveSite,saveGoal,saveProfile,invite,requireOk} from './data.js';
let data=demo(),view='dashboard',site='all',month=today().slice(0,7),isDemo=true,search='',reportStart='',reportEnd='';
const admin=()=>['principal_admin','admin'].includes(data.profile.role);
const realSites=()=>data.sites.filter(s=>s.id!=='__unallocated__');
const siteName=id=>data.sites.find(s=>s.id===id)?.name||id;
const range=()=>view==='reports'&&reportStart&&reportEnd?{start:reportStart,end:reportEnd}:monthRange(month);
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const NAV=[['dashboard','Vue d’ensemble','▦'],['sites','Gestion de sites','⌂'],['purchases','Achats produits','↙'],['returns','Retours & pertes','↗'],['consignments','Consignation','▤'],['reports','Reporting','▥'],['accounts','Gestion comptes','◎']];
const ids=()=>site==='all'?data.sites.map(s=>s.id):[site];
const badge=n=>`<span class="badge ${status(n).cls}">${status(n).text}</span>`;
const card=(label,value,sub,feature=false)=>`<article class="metric ${feature?'feature':''}"><div class="eyebrow">${label}</div><div class="val">${value}</div><div class="mini">${sub}</div></article>`;
function dashboard(){const {start,end}=monthRange(month),p=positions(data,ids(),end),s=summary(data,ids(),start,end),value=p.filter(p=>p.id!=='BAC').reduce((a,p)=>a+p.value,0);return `<div class="headline"><div><div class="eyebrow">Pilotage des emballages</div><h2>Chaque mouvement, un solde juste.</h2></div><button class="gold" data-new="purchase">+ Nouvel achat</button></div><div class="metrics">${card('Solde emballages Brasimba',money(value),status(value).text,true)}${card('Stock des dépôts',qty(p.filter(p=>p.id!=='BAC').reduce((a,p)=>a+p.depot,0)),'Casiers vides et pleins · hors bacs')}${card('Achats de la période',qty(s.purchases),'Casiers reçus depuis Brasimba')}${card('Retours de la période',qty(s.returns),'Casiers retournés · hors consignations')}</div><div class="split"><section class="card"><div class="card-head"><div><h2>Position Brasimba par Bremer</h2><div class="sub">Quantités signées · au ${end.split('-').reverse().join('/')}</div></div><span class="badge">Convention Excel</span></div><div class="table-wrap"><table><thead><tr><th>Natures</th><th class="num">Quantité</th><th class="num">Valeur</th><th>Position</th></tr></thead><tbody>${p.filter(p=>p.id!=='BAC').map(p=>`<tr><td>${p.label}</td><td class="num ${status(p.balance).cls}"><strong>${qty(p.balance)}</strong></td><td class="num">${money(p.value)}</td><td>${badge(p.balance)}</td></tr>`).join('')}</tbody><tfoot><tr><td>Valeur globale emballages</td><td></td><td class="num">${money(value)}</td><td>${badge(value)}</td></tr></tfoot></table></div><div class="card-body explain">− Négatif : Brasimba doit à Rivinter. + Positif : Rivinter doit à Brasimba. Les positions de types différents restent distinctes.</div></section><section class="card"><div class="card-head"><h2>Points d’attention</h2><span class="badge warn">${qty(s.gap)} casiers</span></div><div class="card-body"><div class="eyebrow">Écart de la période</div><div class="recap"><span>Achats</span><strong>${qty(s.purchases)}</strong></div><div class="recap"><span>− Retours emballages</span><strong>${qty(s.returns)}</strong></div><div class="recap total"><span>Écart achats − retours</span><strong>${qty(s.gap)}</strong></div><p class="explain">L’écart mensuel n’est pas le solde Brasimba : il exclut le report, les consignations et les casses.</p><div class="note"><strong>Parc de bacs</strong><br>${qty(p.find(p=>p.id==='BAC').depot)} au dépôt · solde Brasimba ${qty(p.find(p=>p.id==='BAC').balance)}.</div></div></section></div>${siteTable(start,end)}`;}
function siteTable(start,end){return `<section class="card"><div class="card-head"><h2>Situation des sites & axes</h2><span class="sub">Chaque site conserve son propre stock</span></div><div class="table-wrap"><table><thead><tr><th>Site / axe</th><th class="num">Achats</th><th class="num">Retours</th><th class="num">Écart période</th><th class="num">Stock dépôt</th><th class="num">Solde Brasimba</th></tr></thead><tbody>${data.sites.filter(s=>ids().includes(s.id)).map(s=>{const a=summary(data,[s.id],start,end),p=positions(data,[s.id],end).filter(p=>p.id!=='BAC');return `<tr><td><strong>${h(s.name)}</strong> <span class="sub">${s.kind}</span></td><td class="num">${qty(a.purchases)}</td><td class="num">${qty(a.returns)}</td><td class="num ${a.gap>0?'bad':'good'}">${qty(a.gap)}</td><td class="num">${qty(p.reduce((n,p)=>n+p.depot,0))}</td><td class="num">${money(p.reduce((n,p)=>n+p.value,0))}</td></tr>`}).join('')}</tbody></table></div></section>`;}
function render(){
 const nav=NAV.filter(n=>n[0]!=='accounts'||admin()),{start,end}=range();
 const pages={dashboard,sites:sitesPage,purchases:()=>journal(['purchase']),returns:()=>journal(['return','depot_loss','factory_breakage']),consignments:()=>journal(['consignment','bottle_consignment']),reports:reportsPage,accounts:accountsPage};
 document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><img src="/logo-rivinter.png" alt="Logo Rivinter"><strong>RIVINTER SARLU</strong><small>GESTION DES EMBALLAGES</small></div><nav class="nav"><small>ESPACE DE GESTION</small>${nav.map(([id,label,ico])=>`<button data-view="${id}" class="${view===id?'active':''}"><span class="ico" aria-hidden="true">${ico}</span>${label}</button>`).join('')}</nav><div class="sidefoot"><strong>${h(data.profile.full_name||data.profile.email||'Rivinter')}</strong>${isDemo?'Démonstration sans sauvegarde':h(data.profile.role)}<br><button id="logout" class="linkbtn" style="color:#e6edf5;margin-top:12px">${isDemo?'Connexion réelle':'Déconnexion'}</button></div></aside><main class="main"><header class="topbar"><div><h1>${nav.find(n=>n[0]===view)?.[1]||'Vue d’ensemble'}</h1><div class="sub">Stocks, mouvements et positions d’emballages</div></div><div class="filters"><label><span>Période</span><input id="month" type="month" value="${month}"></label><label><span>Site / axe</span><select id="site"><option value="all">${admin()?'Tous les sites & axes':'Mon site'}</option>${data.sites.map(s=>`<option value="${s.id}" ${site===s.id?'selected':''}>${h(s.name)}</option>`).join('')}</select></label><button id="refresh" title="Actualiser les données">↻ Actualiser</button></div><select class="mobile-nav" id="mobile" aria-label="Module">${nav.map(([id,label])=>`<option value="${id}" ${view===id?'selected':''}>${label}</option>`).join('')}</select></header><div class="content"><div class="print-head"><h1>RIVINTER SARLU · Suivi des emballages</h1><p>${h(site==='all'?'Consolidation des sites autorisés':siteName(site))} · Du ${start} au ${end} · Édité le ${today()}${isDemo?' · DÉMONSTRATION FICTIVE':''}</p></div>${isDemo?'<div class="banner">DÉMONSTRATION · Données fictives. Les simulations disparaissent au rechargement. Aucun lien avec votre base réelle.</div>':''}${!isDemo&&data.unallocated?'<div class="banner">Un report usine historique n’est pas affecté aux sites. Il reste visible séparément dans la consolidation ; il n’est pas réparti arbitrairement.</div>':''}${pages[view]?.()||dashboard()}</div></main></div>`;
 if(!admin())document.querySelectorAll('[data-new]').forEach(b=>b.remove());
}
function journal(kinds){const {start,end}=monthRange(month),rows=summary(data,ids(),start,end).rows.filter(m=>kinds.includes(m.kind));
 const groups=new Map();for(const m of rows){if(!groups.has(m.op_id))groups.set(m.op_id,{...m,lines:[],total:0});const g=groups.get(m.op_id);g.lines.push(m);g.total+=Number(m.amount)}
 const selected=[...groups.values()].filter(g=>`${g.ref} ${siteName(g.location_id)} ${KINDS[g.kind]}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));
 const actions=view==='purchases'?[['purchase','Nouvel achat']]:view==='returns'?[['return','Nouveau retour'],['depot_loss','Perte / vol au dépôt'],['factory_breakage','Casse chez Brasimba']]:[['consignment','Nouvelle consignation']];
 const canceled=(data.operations||[]).filter(o=>o.cancelled_at&&ids().includes(o.location_id)&&o.date>=start&&o.date<=end&&(kinds.includes(o.kind)||o.kind==='consignment'&&kinds.includes('bottle_consignment')));
 return `<div class="toolbar"><label><span>Rechercher par référence ou site</span><input id="search" value="${h(search)}" placeholder="Référence, site… (Entrée)"></label><div class="actions">${admin()?actions.map(([k,l])=>`<button class="${k===actions[0][0]?'gold':''}" data-new="${k}">+ ${l}</button>`).join(''):''}</div></div>${view==='consignments'?'<div class="note" style="margin-bottom:20px">Un seul BV peut contenir des emballages et plusieurs types de bouteilles. Son montant est comparé à la somme de toutes les lignes. Les nouvelles consignations d’emballages diminuent le dépôt ; les bouteilles consomment les bacs nécessaires.</div>':''}<section class="card"><div class="card-head"><h2>Historique des opérations</h2><span class="badge">${selected.length} opération(s)</span></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Référence</th><th>Site</th><th>Opération</th><th class="num">Lignes</th><th class="num">Valeur</th><th>Action</th></tr></thead><tbody>${selected.map(g=>`<tr><td>${h(g.date)}</td><td><strong>${h(g.ref||'Sans référence')}</strong>${g.legacy?' <span class="badge warn">Historique</span>':''}</td><td>${h(siteName(g.location_id))}</td><td>${KINDS[g.kind]}${g.lines.some(l=>l.kind!==g.kind)?' · mixte':''}</td><td class="num">${g.lines.length}</td><td class="num">${money(g.total)}</td><td><button data-detail="${h(g.op_id)}">Voir le détail</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Aucune opération pour cette période.</td></tr>'}</tbody></table></div></section>${canceled.length?`<section class="card"><div class="card-head"><h2>Annulations conservées dans l’historique</h2></div><div class="card-body">${canceled.map(o=>`<p><strong>${h(o.ref)}</strong> · ${h(siteName(o.location_id))} · ${h(o.cancel_reason)} · ${h(o.cancelled_at)}</p>`).join('')}</div></section>`:''}`;
}
function sitesPage(){const {end}=monthRange(month);return `<div class="headline"><div><h2>Sites indépendants, vision consolidée</h2><p class="sub">Le stock dépôt comprend les casiers vides et ceux contenant des produits.</p></div>${admin()?'<button class="gold" data-site-new>+ Ajouter un site / axe</button>':''}</div><div class="note" style="margin-bottom:20px">Les reports sont des références d’ouverture, pas des mouvements. Ils ne sont modifiables que si le site n’a aucun mouvement et si le stock initial n’est pas verrouillé. Les objectifs sont en quantité uniquement.</div>${realSites().filter(s=>ids().includes(s.id)).map(s=>{const p=positions(data,[s.id],end),target=data.objectives.find(o=>o.location_id===s.id&&o.month===month)?.qty||0;return `<section class="card"><div class="card-head"><h2>${h(s.name)} <span class="badge">${h(s.kind)}</span></h2><div class="actions">${admin()?`<button data-opening="${s.id}">Stock initial & report</button><button data-goal="${s.id}">Objectif ${qty(target)} casiers</button>`:`<span>Objectif : ${qty(target)} casiers</span>`}</div></div><div class="table-wrap"><table><thead><tr><th>Bremer</th><th class="num">Stock dépôt</th><th class="num">Solde Brasimba signé</th><th class="num">Position parc = − solde</th><th class="num">Valeur du solde</th></tr></thead><tbody>${p.map(t=>`<tr><td>${t.label}</td><td class="num ${t.depot<0?'bad':''}">${qty(t.depot)}</td><td class="num ${status(t.balance).cls}">${qty(t.balance)}</td><td class="num">${qty(t.park)}</td><td class="num">${money(t.value)}</td></tr>`).join('')}</tbody></table></div></section>`}).join('')||'<div class="empty">Aucun site affecté à ce compte.</div>'}`;}
function reportsPage(){const {start,end}=range(),s=summary(data,ids(),start,end),p=positions(data,ids(),end),goal=data.objectives.filter(o=>ids().includes(o.location_id)&&o.month===month).reduce((n,o)=>n+Number(o.qty),0),standard=start===monthRange(month).start&&end===monthRange(month).end,remaining=Math.max(0,goal-s.purchases),days=end<today()?0:Math.round((new Date(end+'T12:00:00')-new Date((start>today()?start:today())+'T12:00:00'))/86400000)+1;
 return `<div class="toolbar no-print"><div class="actions"><label><span>Du</span><input type="date" id="reportStart" value="${start}"></label><label><span>Au</span><input type="date" id="reportEnd" value="${end}"></label><button id="applyRange">Appliquer</button><button id="resetRange">Mois sélectionné</button></div><div class="actions"><button id="csv">Exporter CSV</button><button class="gold" id="print">PDF / Imprimer</button></div></div><div class="metrics">${card('Objectif réalisé',standard&&goal?`${qty(s.purchases)} / ${qty(goal)}`:qty(s.purchases),standard&&goal?`${qty(s.purchases/goal*100)} % de l’objectif`:'Objectif non défini ou période personnalisée')}${card('Rythme suggéré',!standard||!goal?'Non applicable':!days?'Période clôturée':remaining?`${qty(Math.ceil(remaining/days))} / jour`:'Objectif atteint','Basé sur les jours calendaires restants')}${card('Retours emballages',qty(s.returns),`${qty(s.bacs)} bacs retournés séparément`)}${card('Écart de la période',qty(s.gap),s.gap>0?'Achats supérieurs aux retours':s.gap<0?'Retours supérieurs aux achats':'Achats et retours équilibrés',true)}</div>${siteTable(start,end)}<div class="split"><section class="card"><div class="card-head"><h2>Rapprochement du solde Brasimba</h2></div><div class="card-body">${TYPES.map(t=>{const closing=p.find(p=>p.id===t.id),delta=s.rows.filter(m=>m.bremer_id===t.id).reduce((n,m)=>n+Number(m.balance_delta),0);return `<div class="recap"><span>${t.short}</span><span>${qty(closing.balance-delta)} ouverture + (${qty(delta)}) mouvements = <strong>${qty(closing.balance)}</strong></span></div>`}).join('')}<p class="explain">Les bacs sont suivis séparément. Un solde négatif représente une créance d’emballages de Rivinter sur Brasimba.</p></div></section><section class="card"><div class="card-head"><h2>Événements de la période</h2></div><div class="card-body"><div class="recap"><span>Consignations (hors bacs)</span><strong>${qty(s.consignments)}</strong></div><div class="recap"><span>Pertes dépôt</span><strong>${qty(s.loss)}</strong></div><div class="recap"><span>Casses chez Brasimba</span><strong>${qty(s.breakage)}</strong></div><p class="explain">Un écart achats − retours positif indique un retour inférieur aux achats de la période, pas nécessairement une dette finale : tenir compte des reports, consignations et casses.</p></div></section></div>`;}
function accountsPage(){if(!admin())return '<div class="empty">Accès réservé.</div>';return `<div class="headline"><h2>Accès et affectations</h2><button class="gold" id="invite">+ Créer un compte</button></div><section class="card"><div class="card-head"><h2>Comptes utilisateurs</h2></div><div class="table-wrap"><table><thead><tr><th>Nom</th><th>Email</th><th>Rôle</th><th>Site</th><th>État</th><th>Action</th></tr></thead><tbody>${(data.profiles||[]).map(p=>`<tr><td>${h(p.full_name)}</td><td>${h(p.email)}</td><td>${h(p.role)}</td><td>${h(p.location_id?siteName(p.location_id):'Tous')}</td><td><span class="badge ${p.active?'good':'bad'}">${p.active?'Actif':'Désactivé'}</span></td><td>${p.id!==data.profile.id&&(data.profile.role==='principal_admin'||p.role!=='principal_admin')?`<button data-profile="${p.id}">Modifier</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Connectez votre base pour gérer les comptes réels.</td></tr>'}</tbody></table></div></section><div class="note">Aucune réinitialisation globale n’est proposée dans cette version. Les opérations se corrigent par annulation motivée, sans effacement de l’historique.</div>`;}
function openModal(title,body){const d=document.querySelector('#modal');d.innerHTML=`<header class="card-head"><h2 id="dialog-title">${h(title)}</h2><button type="button" data-close aria-label="Fermer">×</button></header>${body}`;d.setAttribute('aria-labelledby','dialog-title');d.showModal();}
function close(){document.querySelector('#modal').close()}
function notice(text){const t=document.querySelector('#toast');t.textContent=text;t.style.display='block';setTimeout(()=>t.style.display='none',5000)}
const field=(label,name,type='text',value='',extra='')=>`<label><span>${label}</span><input name="${name}" type="${type}" value="${h(value)}" ${extra}></label>`;
const sitesSelect=(selected=site)=>`<label><span>Site / axe</span><select name="location_id" required>${realSites().map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${h(s.name)}</option>`).join('')}</select></label>`;
const footer=label=>`<div class="error hidden" role="alert" id="formError"></div><footer><button type="button" data-close>Annuler</button><button class="gold" type="submit">${label}</button></footer>`;
function lineMarkup(kind){return `<div class="formline">${kind==='consignment'?'<label><span>Nature</span><select name="line_kind"><option value="consignment">Emballages</option><option value="bottle_consignment">Bouteilles</option></select></label>':`<label><span>Opération</span><input value="${KINDS[kind]}" readonly></label>`}<label><span>${kind==='purchase'?'Produit':'Bremer'}</span><select name="item">${(kind==='purchase'?data.products:TYPES).map(t=>`<option value="${t.id}">${h(t.name||t.label)}</option>`).join('')}</select></label><label><span class="quantity-label">Quantité</span><input name="quantity" type="number" min="1" step="1" required></label><button type="button" data-remove aria-label="Retirer la ligne">×</button><div class="wide explain line-info"></div></div>`;}
function newOperation(kind){if(!admin())return; if(!realSites().length){notice('Créez un site avant de saisir une opération.');return}openModal(kind==='consignment'?'Consignation · BV unique':KINDS[kind],`<form id="operationForm" data-kind="${kind}" data-request="${crypto.randomUUID()}"><div class="formgrid">${field('Date','date','date',today(),`required max="${today()}"`)}${sitesSelect()}${field(kind==='consignment'?'Numéro du BV':'Référence / facture','ref','text','','required maxlength="120"')}${kind==='consignment'?field('Montant total du BV (Fc)','bv_amount','number','','required min="0.01" step="0.01"'):''}<label class="wide"><span>${['depot_loss','factory_breakage'].includes(kind)?'Motif obligatoire':'Observation'}</span><textarea name="note" ${['depot_loss','factory_breakage'].includes(kind)?'required minlength="3"':''}></textarea></label></div><div id="lines">${lineMarkup(kind)}</div><button type="button" id="addLine">+ Ajouter une ligne</button><div id="operationPreview" class="note" style="margin-top:15px">Renseignez les quantités pour afficher l’impact.</div>${footer(isDemo?'Simuler (non sauvegardé)':'Enregistrer l’opération')}</form>`);}
function readLines(form){const kind=form.dataset.kind;return [...form.querySelectorAll('.formline')].map(line=>{const mode=kind==='consignment'?line.querySelector('[name=line_kind]').value:kind;const item=line.querySelector('[name=item]').value;const count=Number(line.querySelector('[name=quantity]').value);const product=kind==='purchase'?data.products.find(p=>p.id===item):null;const result=normalizeLine(mode,product?.bremer_id||item,count);if(product){const override=data.prices?.find(p=>p.product_id===item&&p.location_id===form.elements.location_id.value);result.product_id=item;result.amount=count*Number(override?.price??product.price)}return {...result,input_quantity:count};});}
function preview(){const form=document.querySelector('#operationForm');if(!form)return;try{const lines=readLines(form),total=lines.reduce((n,l)=>n+l.amount,0),bacs=-lines.reduce((n,l)=>n+l.bac_delta,0);form.querySelectorAll('.formline').forEach((line,i)=>{const l=lines[i];line.querySelector('.quantity-label').textContent=l.kind==='bottle_consignment'?'Bouteilles':'Casiers / bacs';line.querySelector('.line-info').textContent=`${qty(l.quantity)} ${l.bremer_id==='BAC'?'bac(s)':'casier(s)'} · ${money(l.amount)} · dépôt ${qty(l.depot_delta)} · solde signé ${qty(l.balance_delta)}${l.bac_delta?` · bacs ${qty(l.bac_delta)}`:''}`});const bv=Number(form.elements.bv_amount?.value);document.querySelector('#operationPreview').innerHTML=`<strong>Total calculé : ${money(total)}</strong>${bacs?` · ${qty(bacs)} bacs nécessaires`:''}${form.dataset.kind==='consignment'?`<br><span class="${total===bv?'good':'bad'}">Écart avec le BV : ${money(bv-total)}</span>`:''}`;}catch(e){document.querySelector('#operationPreview').textContent=e.message;}}
function detail(id){const lines=data.movements.filter(m=>m.op_id===id);if(!lines.length)return;const op=lines[0],header=data.operations?.find(o=>o.id===id);openModal(`Opération ${op.ref||'historique'}`,`<div class="card-body"><p>${h(siteName(op.location_id))} · ${h(op.date)}</p>${op.legacy?'<div class="banner">Historique conservé : les anciennes consignations gardent leurs effets d’origine. Pas de modification automatique de leur stock dépôt. Toute conversion historique nécessite un rapprochement validé.</div>':''}<div class="table-wrap"><table><thead><tr><th>Nature</th><th>Bremer</th><th class="num">Casiers / bacs</th><th class="num">Dépôt Δ</th><th class="num">Solde Δ</th><th class="num">Bacs Δ</th><th class="num">Valeur</th></tr></thead><tbody>${lines.map(l=>`<tr><td>${KINDS[l.kind]}</td><td>${TYPES.find(t=>t.id===l.bremer_id)?.short||h(l.bremer_id)}</td><td class="num">${qty(l.quantity)}</td><td class="num">${qty(l.depot_delta)}</td><td class="num">${qty(l.balance_delta)}</td><td class="num">${qty(l.bac_delta)}</td><td class="num">${money(l.amount)}</td></tr>`).join('')}</tbody></table></div>${header?.bv_amount?`<p>Montant du BV : <strong>${money(header.bv_amount)}</strong></p>`:''}<p>${h(op.note||'Aucune observation.')}</p>${!op.legacy&&admin()?`<form id="cancelForm" data-id="${h(id)}">${field('Motif de l’annulation','reason','text','','required minlength="3"')}<p class="explain">L’opération sera neutralisée dans les soldes, mais conservée dans l’historique. Une annulation qui rend le dépôt négatif sera refusée.</p>${footer('Confirmer l’annulation')}</form>`:''}</div>`);}
function editOpening(id){const active=data.movements.some(m=>m.location_id===id);if(data.locked||active){notice('Report protégé : stock verrouillé ou mouvements déjà présents.');return}openModal('Stock initial · '+siteName(id),`<form id="openingForm" data-site="${id}"><div class="note">Dépôt : quantités physiques positives. Solde Brasimba signé : négatif si Brasimba doit à Rivinter, positif dans le cas contraire. Ces valeurs précèdent tous les mouvements du site.</div><div class="table-wrap"><table><thead><tr><th>Bremer</th><th>Dépôt initial</th><th>Solde Brasimba initial signé</th></tr></thead><tbody>${TYPES.map(t=>{const o=data.openings.find(o=>o.location_id===id&&o.bremer_id===t.id);return `<tr><td>${t.label}</td><td><input aria-label="Dépôt ${t.short}" type="number" step="1" min="0" required name="depot_${t.id}" value="${o?.depot||0}"></td><td><input aria-label="Solde ${t.short}" type="number" step="1" required name="balance_${t.id}" value="${o?.balance||0}"></td></tr>`}).join('')}</tbody></table></div>${footer('Enregistrer les reports')}</form>`);}
function newSite(){openModal('Ajouter un site ou un axe',`<form id="siteForm"><div class="formgrid">${field('Nom','name','text','','required maxlength="100"')}<label><span>Type</span><select name="kind"><option>Site</option><option>Axe</option></select></label></div>${footer('Créer')}</form>`)}
function goal(id){const value=data.objectives.find(o=>o.location_id===id&&o.month===month)?.qty||0;openModal(`Objectif · ${siteName(id)} · ${month}`,`<form id="goalForm" data-site="${id}">${field('Objectif en casiers uniquement','qty','number',value,'required min="0" step="1"')}${footer('Enregistrer')}</form>`)}
function userForm(id){const p=data.profiles?.find(p=>p.id===id),principal=data.profile.role==='principal_admin';openModal(p?'Modifier un compte':'Créer un compte',`<form id="userForm" data-id="${h(id||'')}"><div class="formgrid">${!p?field('Nom complet','full_name','text','','required')+field('Email','email','email','','required')+field('Mot de passe provisoire','password','password','','required minlength="8" autocomplete="new-password"'):''}<label><span>Rôle</span><select name="role">${['user','admin',...(principal?['principal_admin']:[])].map(r=>`<option value="${r}" ${p?.role===r?'selected':''}>${r==='user'?'Utilisateur':r==='admin'?'Administrateur':'Administrateur principal'}</option>`).join('')}</select></label>${sitesSelect(p?.location_id)}${p?`<label><span>État</span><select name="active"><option value="true" ${p.active?'selected':''}>Actif</option><option value="false" ${!p.active?'selected':''}>Désactivé</option></select></label>`:''}</div><p class="explain">Les utilisateurs consultent uniquement leur site. Les administrateurs accèdent à la consolidation.</p>${footer(p?'Enregistrer':'Créer le compte')}</form>`)}
function exportCsv(){const {start,end}=range(),rows=[['Site','Début','Fin','Achats casiers','Retours casiers','Retours bacs','Écart achats-retours','Stock dépôt hors bacs','Solde Brasimba casiers','Valeur solde hors bacs Fc','Solde bacs','Valeur bacs Fc']];for(const id of ids()){const s=summary(data,[id],start,end),p=positions(data,[id],end),b=p.find(t=>t.id==='BAC'),cases=p.filter(t=>t.id!=='BAC');rows.push([siteName(id),start,end,s.purchases,s.returns,s.bacs,s.gap,cases.reduce((n,p)=>n+p.depot,0),cases.reduce((n,p)=>n+p.balance,0),cases.reduce((n,p)=>n+p.value,0),b.balance,b.value]);}const csv='\ufeff'+rows.map(r=>r.map(c=>`"${String(typeof c==='string'&&/^[=+\-@]/.test(c)?"'"+c:c).replaceAll('"','""')}"`).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`rivinter-${start}-${end}${isDemo?'-DEMONSTRATION':''}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function refresh(){if(!isDemo)data=await load();render()}
function login(message=''){document.querySelector('#app').innerHTML=`<main class="login"><section class="card"><img src="/logo-rivinter.png" alt="Rivinter"><div class="eyebrow">Gestion des emballages</div><h1>Bienvenue chez Rivinter</h1><p class="explain">Connectez-vous pour retrouver les stocks et mouvements de votre site.</p>${message?`<div class="error" role="alert">${h(message)}</div>`:''}<form id="loginForm">${field('Email','email','email','','required autocomplete="username"')}${field('Mot de passe','password','password','','required autocomplete="current-password"')}${footer('Se connecter')}</form><button id="demo" style="width:100%">Explorer la démonstration</button>${!db?'<p class="explain">La connexion réelle nécessite les variables Supabase du projet. Ne saisissez aucune clé privée dans cette page.</p>':''}</section></main>`;}
document.addEventListener('change',e=>{if(e.target.closest('#operationForm'))preview();if(e.target.id==='month'){month=e.target.value||month;reportStart='';reportEnd='';render()}if(e.target.id==='site'){site=e.target.value;render()}if(e.target.id==='mobile'){view=e.target.value;search='';render()}if(e.target.id==='search'){search=e.target.value;render()}});
document.addEventListener('input',e=>{if(e.target.closest('#operationForm'))preview()});
document.addEventListener('click',async e=>{try{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;search='';render()}else if(b.hasAttribute('data-close'))close();else if(b.dataset.new)newOperation(b.dataset.new);else if(b.dataset.detail)detail(b.dataset.detail);else if(b.dataset.opening)editOpening(b.dataset.opening);else if(b.dataset.goal)goal(b.dataset.goal);else if(b.dataset.profile)userForm(b.dataset.profile);else if(b.hasAttribute('data-site-new'))newSite();else if(b.hasAttribute('data-remove')){if(document.querySelectorAll('.formline').length>1)b.closest('.formline').remove();preview()}else if(b.id==='addLine'){document.querySelector('#lines').insertAdjacentHTML('beforeend',lineMarkup(document.querySelector('#operationForm').dataset.kind));preview()}else if(b.id==='applyRange'){const a=document.querySelector('#reportStart').value,z=document.querySelector('#reportEnd').value;if(!a||!z||a>z)throw Error('Choisissez une période valide.');reportStart=a;reportEnd=z;render()}else if(b.id==='resetRange'){reportStart='';reportEnd='';render()}else if(b.id==='print')window.print();else if(b.id==='csv')exportCsv();else if(b.id==='invite')userForm();else if(b.id==='refresh')await refresh();else if(b.id==='logout'){if(db&&!isDemo)await db.auth.signOut();isDemo=true;data=demo();login()}else if(b.id==='demo'){isDemo=true;data=demo();view='dashboard';site='all';render()}}catch(error){notice(error.message)}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button[type=submit]'),errorBox=form.querySelector('#formError');if(button?.disabled)return;if(button)button.disabled=true;if(errorBox)errorBox.classList.add('hidden');try{
 const fields=Object.fromEntries(new FormData(form));
 if(form.id==='loginForm'){if(!db)throw Error('Connexion non configurée. La démonstration reste accessible.');requireOk(await db.auth.signInWithPassword({email:fields.email,password:fields.password}));data=await load();isDemo=false;site='all';view='dashboard';render();return}
 if(!admin())throw Error('Action réservée aux administrateurs.');
 if(form.id==='operationForm'){
  const lines=readLines(form);if(!lines.length)throw Error('Ajoutez une ligne.');const total=lines.reduce((n,l)=>n+l.amount,0);
  if(form.dataset.kind==='consignment'&&Number(fields.bv_amount)!==total)throw Error(`Le BV doit correspondre au total de ${money(total)}.`);
  const payload={request_id:form.dataset.request,location_id:fields.location_id,date:fields.date,kind:form.dataset.kind,ref:fields.ref.trim(),bv_amount:Number(fields.bv_amount)||null,note:fields.note,lines:lines.map(l=>({kind:l.kind,bremer_id:l.bremer_id,product_id:l.product_id,quantity:l.input_quantity}))};
  if(isDemo){const p=positions(data,[payload.location_id],payload.date);for(const t of TYPES){const delta=lines.reduce((n,l)=>n+(l.bremer_id===t.id?l.depot_delta:0)+(t.id==='BAC'?l.bac_delta:0),0);if(p.find(p=>p.id===t.id).depot+delta<0)throw Error('Stock de démonstration insuffisant : '+t.short)}data.movements.push(...lines.map((l,i)=>({...l,id:payload.request_id+'-'+i,op_id:payload.request_id,date:payload.date,location_id:payload.location_id,ref:payload.ref,note:payload.note})));}
  else await postOperation(payload);
 }else if(form.id==='cancelForm'){
  if(isDemo){data.movements=data.movements.filter(m=>m.op_id!==form.dataset.id)}else await cancelOperation(form.dataset.id,fields.reason);
 }else if(form.id==='openingForm'){
  const rows=TYPES.map(t=>({bremer_id:t.id,depot:Number(fields['depot_'+t.id]),balance:Number(fields['balance_'+t.id])}));
  if(isDemo){for(const r of rows){Object.assign(data.openings.find(o=>o.location_id===form.dataset.site&&o.bremer_id===r.bremer_id),r)}}else await saveOpening(form.dataset.site,rows);
 }else if(form.id==='goalForm'){
  const value=Number(fields.qty);if(!Number.isSafeInteger(value)||value<0)throw Error('Objectif entier positif ou nul requis.');
  if(isDemo){data.objectives=data.objectives.filter(o=>!(o.location_id===form.dataset.site&&o.month===month));data.objectives.push({location_id:form.dataset.site,month,qty:value})}else await saveGoal(form.dataset.site,month,value);
 }else if(form.id==='siteForm'){
  const id='site-'+crypto.randomUUID();if(!fields.name.trim())throw Error('Nom obligatoire.');if(isDemo){data.sites.push({id,name:fields.name.trim(),kind:fields.kind});data.openings.push(...TYPES.map(t=>({location_id:id,bremer_id:t.id,date:'0001-01-01',depot:0,balance:0})))}else await saveSite(id,fields.name.trim(),fields.kind);
 }else if(form.id==='userForm'){
  if(isDemo)throw Error('Les comptes réels se gèrent uniquement après connexion.');
  const location_id=fields.role==='user'?fields.location_id:null;
  if(form.dataset.id)await saveProfile(form.dataset.id,{role:fields.role,location_id,active:fields.active==='true'});else await invite({...fields,location_id});
 }
 close();notice(isDemo?'Simulation appliquée — aucune sauvegarde réelle.':'Enregistrement confirmé.');await refresh();
 }catch(error){if(errorBox&&document.contains(errorBox)){errorBox.textContent=error.message;errorBox.classList.remove('hidden')}else notice(error.message)}finally{if(button)button.disabled=false}});
async function boot(){if(!db){render();return}try{const {data:session}=await db.auth.getSession();if(session.session){data=await load();isDemo=false;render()}else login()}catch(e){login(e.message+' Vérifiez notamment la migration Rivinter v2.')}}
boot();
// Optional agent interface: same visible flows, never bypasses confirmation or RLS.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_packaging_position',description:'Lire les positions du périmètre actuellement affiché, sans écriture.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('Aucun paramètre attendu.');if(!document.querySelector('.layout'))throw Error('Connexion requise.');return {demo:isDemo,period:range(),positions:positions(data,ids(),range().end)};}});
 register({name:'start_packaging_operation',description:'Ouvrir une saisie à compléter et confirmer manuellement. Ne crée aucun mouvement.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['purchase','return','consignment','depot_loss','factory_breakage']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='kind')||!['purchase','return','consignment','depot_loss','factory_breakage'].includes(input.kind))throw Error('Type invalide.');if(!document.querySelector('.layout')||!admin())throw Error('Accès refusé.');if(!realSites().length)throw Error('Créez un site.');if(document.querySelector('#modal').open)throw Error('Fermez la saisie en cours.');newOperation(input.kind);return {status:'form_opened',saved:false};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
